# Generated by Django 3.0.5 on 2020-05-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaires', '0002_answear'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answear',
            new_name='Answer',
        ),
    ]
