# Generated by Django 3.0.5 on 2020-05-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionnaires', '0003_auto_20200513_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
